# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  # vmImage: 'ubuntu-latest'
  vmImage:  'ubuntu-18.04'

variables:
  buildConfiguration: 'Release'

steps:
- task:  DotNetCoreCLI@2
  inputs:
    command:  'restore'
    feedsToUse: 'select'
    vstsFeed: 'my-vsts-feed'
- task:  DotNetCoreCLI@2
  inputs:
    command:  'build'
    arguments:  '--configuration $(buildCOnfiguration)'
  displayName:  'dotnet build $(buildConfiguration)'

- task:  DotNetCoreCLI@2
  displayName:  Build
  inputs:
    command:  build
    projects:  '**/*.csproj'
    arguments:  '--configuration $(buildConfiguration)'
    
- task:  UseDotNet@2
  inputs:
    version:  '5.0.x'
    includePreviewVersions: true

- task:  UseDotNet@2
  inputs:
    version:  '3.0.x'
    packageType:  runtime

- task:  DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command:  test
    projects:  '**/test-library/*.csproj'
    arguments:  '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourceDirectory)/TestResults/Coverage/'

- task:  PublishTestResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourceDirectory)/**/coverage.cobertura.xml'
